#pragma config(Sensor, in1,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in2,    flipPot,        sensorPotentiometer)
#pragma config(Motor,  port1,           wristMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          flipMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float wristSpeed = 0;
float flipSpeed = 0;
float wristPosition = 0;
float wristSeek = -1;
float wristSeekRate = 5;
float flipPosition = 0;
float flipSeek = -1;
float flipSeekRate = -3;
int flipStep = -1;
float wristDownSpeed = 25;
float wristHoldPosition = 25;
bool quickToss = false;


// bottom-top = 3200-500;
task main()
{
	bool justFlipped = false;
	bool justRaised = false;
	while (true) {

		// Track current position, set speeds to 0 at start of each loop
		wristSpeed = 0;
		flipSpeed = 0;
		flipPosition = -(-4000.0 + (float)SensorValue(flipPot)) / (40-4);
		wristPosition = (3200.0 - (float)SensorValue(wristPot)) / (32.0-5.0) - (10*(flipPosition < 50));

		// Auto-mini-routines
		if (vexRT[Btn5D]) {
			if (!justFlipped) {
				if (flipPosition > 50) flipSeek = 1; else flipSeek = 100;
				justFlipped = true;
			}
		}
		else {
			justFlipped = false;
		}

		if (vexRT[Btn5U]) {
			if (!justRaised) {
				if (wristPosition > 30) wristSeek = 1; else wristSeek = 60;
				justRaised = true;
			}
		}
		else {
			justRaised = false;
		}

		if (vexRT[Btn6D]) {
			wristSeek = 1;
			flipSeek = 100;
		}

		// Auto-flip
		if (vexRT[Btn6U]) {
			flipStep = 1;
			quickToss = false;
		}
		if (vexRT[Btn8D]) {
			flipStep = 1;
			quickToss = true;
		}

		if (flipStep == 1) {
			if (!vexRT[Btn6U]) {
				flipStep++;
			}
		}
		if (flipStep == 2) {
			wristSeek = 60;
			if (wristPosition > 50) {
				flipStep++;
			}
		}
		if (flipStep == 3) {
			wristSeek = 60;
			flipSeek = 1;
			if (flipSeek < 30) {
				flipStep++;
				if (quickToss) {
					flipStep++;
				}
				clearTimer(T1);
			}
		}
		if (flipStep == 4) {
			wristSeek = 60 - (wristDownSpeed*time1(T1))/1000;					// 2 sec to go 20, 10/1000 ms
			flipSeek = 1;
			if (wristPosition < wristHoldPosition) {
				flipStep = 6;
			}
		}
		if (flipStep == 5) {
			wristSeek = 60;
			flipSeek = 1;
			if (flipPosition < 5) {
				flipStep++;
			}
		}
		if (flipStep == 6) {
			flipSeek = 1;
			wristSeek = wristHoldPosition;
			if (wristPosition < wristHoldPosition) {
				flipStep = -1;
				flipSeek = -1;
				wristSeek = wristHoldPosition;
			}
		}

		// Lerps for wrist and flip
		if (wristSeek >= 0) {
			wristSpeed = -(wristSeek - wristPosition) * wristSeekRate;
		}

		if (flipSeek >= 0) {
			flipSpeed = -(flipSeek - flipPosition) * flipSeekRate;
		}

		// Manual overrides
		if (vexRT[Btn7U]) {
			wristSeek = -1;
			flipSeek = -1;
			flipStep = -1;
		}
		if (abs(vexRT[Ch3])>20) {
			wristSpeed = -vexRT[Ch3];
			wristSeek = -1;
		}
		if (abs(vexRT[Ch1])>20) {
			flipSpeed = vexRT[Ch1];
			flipSeek = -1;
		}

		// Send values to motors
		motor[wristMotor] = wristSpeed;
		motor[flipMotor] = flipSpeed;

		// End
		wait1Msec(10);
	}


}
